// Mocks generated by Mockito 5.4.0 from annotations
// in aha_demo/test/app_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:aha_demo/models/auth_state.dart' as _i7;
import 'package:aha_demo/repositories/app_repository.dart' as _i4;
import 'package:aha_demo/repositories/dto/response/users_result_dto.dart' as _i2;
import 'package:aha_demo/repositories/dto/response/users_statistic_dto.dart' as _i3;
import 'package:firebase_auth/firebase_auth.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUsersResultDto_0 extends _i1.SmartFake implements _i2.UsersResultDto {
  _FakeUsersResultDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUsersStatisticDto_1 extends _i1.SmartFake implements _i3.UsersStatisticDto {
  _FakeUsersStatisticDto_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppRepository extends _i1.Mock implements _i4.AppRepository {
  @override
  _i5.Future<_i6.User?> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i5.Future<_i6.User?>.value(),
        returnValueForMissingStub: _i5.Future<_i6.User?>.value(),
      ) as _i5.Future<_i6.User?>);
  @override
  _i5.Future<void> reloadUser() => (super.noSuchMethod(
        Invocation.method(
          #reloadUser,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<String?> getIdToken() => (super.noSuchMethod(
        Invocation.method(
          #getIdToken,
          [],
        ),
        returnValue: _i5.Future<String?>.value(),
        returnValueForMissingStub: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);
  @override
  _i5.Future<_i7.AuthState> getAuthState() => (super.noSuchMethod(
        Invocation.method(
          #getAuthState,
          [],
        ),
        returnValue: _i5.Future<_i7.AuthState>.value(_i7.AuthState.emailVerified),
        returnValueForMissingStub: _i5.Future<_i7.AuthState>.value(_i7.AuthState.emailVerified),
      ) as _i5.Future<_i7.AuthState>);
  @override
  _i5.Future<void> signIn(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> signInWithFacebook() => (super.noSuchMethod(
        Invocation.method(
          #signInWithFacebook,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> register(
    String? email,
    String? password,
    String? displayName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            email,
            password,
            displayName,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> sendEmailVerification() => (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> verifyEmail(String? oobCode) => (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [oobCode],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> updateUserInfo({String? displayName}) => (super.noSuchMethod(
        Invocation.method(
          #updateUserInfo,
          [],
          {#displayName: displayName},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<void> updateUserPassword(
    String? currentPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPassword,
          [
            currentPassword,
            newPassword,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
  @override
  _i5.Future<_i2.UsersResultDto> findUsers(
    int? pageSize,
    String? pageToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findUsers,
          [
            pageSize,
            pageToken,
          ],
        ),
        returnValue: _i5.Future<_i2.UsersResultDto>.value(_FakeUsersResultDto_0(
          this,
          Invocation.method(
            #findUsers,
            [
              pageSize,
              pageToken,
            ],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i2.UsersResultDto>.value(_FakeUsersResultDto_0(
          this,
          Invocation.method(
            #findUsers,
            [
              pageSize,
              pageToken,
            ],
          ),
        )),
      ) as _i5.Future<_i2.UsersResultDto>);
  @override
  _i5.Future<_i3.UsersStatisticDto> findUsersStatistic() => (super.noSuchMethod(
        Invocation.method(
          #findUsersStatistic,
          [],
        ),
        returnValue: _i5.Future<_i3.UsersStatisticDto>.value(_FakeUsersStatisticDto_1(
          this,
          Invocation.method(
            #findUsersStatistic,
            [],
          ),
        )),
        returnValueForMissingStub: _i5.Future<_i3.UsersStatisticDto>.value(_FakeUsersStatisticDto_1(
          this,
          Invocation.method(
            #findUsersStatistic,
            [],
          ),
        )),
      ) as _i5.Future<_i3.UsersStatisticDto>);
}
